# Generated by Django 3.0.3 on 2020-02-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lamguage',
            new_name='language',
        ),
    ]
